### ISSUE TITLE
广告问题

### ISSUE THREAD

**Issue by mushroom1113** [dubuqingfeng/Docker-Web-Images#2]
首先感谢作者，一直在用。
最近出现浏览器弹出广告问题，不是网页的广告，自己不懂这块，
问问是不是ubuntu-shadowsocks引起的？或者作者知不知道由什
么原因引起的？谢谢

**Comment by dubuqingfeng** [comment]
首先看一下网络是否有劫持情况吧。考虑一下是否有无线中间人去劫持。MITM可以导致弹出广告的，以及这个是全部网站的都会出现？
以及你的服务器端是在什么地方部署的。以及是否走的是代理。
这个镜像的Dockerfile也是公开的。我这并没有广告的问题，在灵雀云香港区和do都试过。

**Comment by mushroom1113** [comment]
我这也是在灵雀云香港区部署的，偶尔在浏览器底部或者右侧弹出广告，估计是其它原因导致的吧。谢谢啦
